In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

In [25]:
tourist_data=pd.read_csv("CSVfiles//tourist_data.csv")

In [26]:
tourist_data.head()

Year  Seasons States  Visitors
0  2001        0     GJ     38057
1  2001        1     GJ     38088
2  2001        2     GJ     36788
3  2001        3     GJ     29618
4  2001        0     AP     36554

In [27]:
tourist_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2552 entries, 0 to 2551
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Year      2552 non-null   int64 
 1   Seasons   2552 non-null   int64 
 2   States    2552 non-null   object
 3   Visitors  2552 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 79.9+ KB


In [28]:
x = tourist_data.iloc[:,0:3].values
print('\n')
y = tourist_data.iloc[:,-1].values
# print(x,y)

In [29]:
# tourist_data.iloc[:,-2].value_counts()
x[:116,2]

array(['GJ', 'GJ', 'GJ', 'GJ', 'AP', 'AP', 'AP', 'AP', 'HR', 'HR', 'HR',
       'HR', 'MN', 'MN', 'MN', 'MN', 'SK', 'SK', 'SK', 'SK', 'AR', 'AR',
       'AR', 'AR', 'HP', 'HP', 'HP', 'HP', 'ML', 'ML', 'ML', 'ML', 'TN',
       'TN', 'TN', 'TN', 'AS', 'AS', 'AS', 'AS', 'JH', 'JH', 'JH', 'JH',
       'TG', 'TG', 'TG', 'TG', 'MZ', 'MZ', 'MZ', 'MZ', 'BR', 'BR', 'BR',
       'BR', 'KA', 'KA', 'KA', 'KA', 'NL', 'NL', 'NL', 'NL', 'TR', 'TR',
       'TR', 'TR', 'CG', 'CG', 'CG', 'CG', 'KL', 'KL', 'KL', 'KL', 'OR',
       'OR', 'OR', 'OR', 'UK', 'UK', 'UK', 'UK', 'GA', 'GA', 'GA', 'GA',
       'MP', 'MP', 'MP', 'MP', 'PB', 'PB', 'PB', 'PB', 'UP', 'UP', 'UP',
       'UP', 'MH', 'MH', 'MH', 'MH', 'RJ', 'RJ', 'RJ', 'RJ', 'WB', 'WB',
       'WB', 'WB', 'JK', 'JK', 'JK', 'JK'], dtype=object)

In [30]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,2] = le1.fit_transform(x[:,2])
x[:116,2]

array([6, 6, 6, 6, 0, 0, 0, 0, 8, 8, 8, 8, 15, 15, 15, 15, 22, 22, 22, 22,
       1, 1, 1, 1, 7, 7, 7, 7, 14, 14, 14, 14, 24, 24, 24, 24, 2, 2, 2, 2,
       9, 9, 9, 9, 23, 23, 23, 23, 17, 17, 17, 17, 3, 3, 3, 3, 11, 11, 11,
       11, 18, 18, 18, 18, 25, 25, 25, 25, 4, 4, 4, 4, 12, 12, 12, 12, 19,
       19, 19, 19, 26, 26, 26, 26, 5, 5, 5, 5, 16, 16, 16, 16, 20, 20, 20,
       20, 27, 27, 27, 27, 13, 13, 13, 13, 21, 21, 21, 21, 28, 28, 28, 28,
       10, 10, 10, 10], dtype=object)

# Training

In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [32]:
print(f"Rows in train set : {len(x_train)} \nRows in test set : {len(x_test)}")
print(f"Rows in train set : {len(y_train)} \nRows in test set : {len(y_test)}")

Rows in train set : 2041 
Rows in test set : 511
Rows in train set : 2041 
Rows in test set : 511


In [33]:
# print(x_train)
# print(y_train)

In [34]:
# from sklearn.tree import DecisionTreeRegressor
# model = DecisionTreeRegressor() #14168.453924565109
# from sklearn.linear_model import LinearRegression
# model = LinearRegression() #13276.672420818435
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor() #11318.885464250312
model.fit(x_train,y_train)

RandomForestRegressor()

In [35]:
x_train[:5]

array([[2021, 1, 24],
       [2013, 1, 11],
       [2022, 2, 14],
       [2022, 3, 9],
       [2021, 1, 18]], dtype=object)

In [36]:
someData = x_train[:5]
someLables = y_train[:5]

In [37]:
someLables

array([727068, 456209, 752740, 745782, 711987], dtype=int64)

In [38]:
model.predict(someData)

array([722737.19, 453562.31, 744484.89, 745746.83, 715847.77])

In [39]:
final_predictions = pd.DataFrame(model.predict(x_test))
final_mse = mean_squared_error(y_test,final_predictions)
final_rmse = np.sqrt(final_mse)

In [40]:
final_rmse

11267.815335413994

In [41]:
# import joblib
# joblib.dump(model,'Tourist_prediction')
import pickle


with open('Tourist_prediction.pkl', 'wb') as f:
    pickle.dump(model, f)

# Testing

In [42]:
print(x_test[:3])
print(final_predictions[:3])

[[2001 0 11]
 [2002 2 16]
 [2020 3 26]]
           0
0   31090.99
1   55943.42
2  688236.99


In [43]:
final_predictions.rename(columns={0:'predicted'},inplace=True)
original_Prediction = pd.DataFrame(y_test)
original_Prediction.rename(columns={0 :'original'},inplace = True)
result = pd.concat([original_Prediction,final_predictions],axis=1)

In [44]:
result

original  predicted
0       29271   31090.99
1       59467   55943.42
2      693040  688236.99
3       89609   83973.48
4      646259  642028.08
..        ...        ...
506    329310  310063.37
507    399406  390650.49
508    579622  578578.77
509    233377  233497.62
510    474468  491287.20

[511 rows x 2 columns]

In [45]:
import joblib

# Load the model from the pickle file
my_model = joblib.load('Tourist_prediction.pkl')

# Making predictions on new data
new_data = [[2005, 3, 0]]
predicted_values = my_model.predict(new_data)

# Displaying the prediction result
print(predicted_values)


[155400.16]


In [46]:
pd.DataFrame(my_model.predict([[2005,3,0]]))

0
0  155400.16